### ISSUE TITLE
Add Node Presets

### ISSUE THREAD

**Issue by GeneralProtectionFault** [BlenderKit/platform#13]
### Is your feature request related to a problem or weakness of addon? Please describe.

Currently, BlenderKit allows us to upload & download materials, but not individual nodes or group nodes.  We can only replace a material entirely.

### Describe the solution you'd like

While Blender itself has the ability to save Node Presets via the addon or the Asset Library, there does not appear to be an intuitive way to share node presets with the community.  If BlenderKit supported Nodes & Node Groups (Custom nodes), there could be another section which could place the selected node(s) on the currently selected material.

This would be useful, not only to non-destructively replace a material, but augment an existing material.  An example would be a procedural shader that overlays a decal or pattern onto an object.  If an object already had a complex material, the node could be added to it, and the user would also gain the ability to combine materials.

```[tasklist]
### Tasks
- [x] Add asset type nodegroup on server
- [x] Invent category system
- [ ] Deploy category system
- [x] Implement nodegroup in addon
- [x] Add appended nodegroup into editor if possible
- [ ] support dragdrop into editors.
```

**Comment by agajdosi** [comment]
FYI @vilemduha

**Comment by agajdosi** [comment]
I have proposed this several time, idea got negative feedback and was rejected. Cannot do more, RN. Removing my assignment.

**Comment by PetrDlouhy** [comment]
Assigning @vilemduha. Setting priority at High. @vilemduha  please evaluate the issue and lower it if needed.

**Comment by GeneralProtectionFault** [comment]
The nature of the negative feedback might be worth considering (I don't know what it was).  One downside I could imagine is that this sort of necessitates a bit more familiarity with Blender.  It wouldn't be "click this and forget it" the way you can with an entire material, which is nice but considerably less powerful.  The good ol' power vs. responsibility catch 22.

There's also a question of UV mapping, but in my head, this would be most useful for procedural stuff.  Others folks would probably have more thoughts than I do about it, though.

It might also be messy to implement, not sure.  If it's the usability, I would suggest just having the Node Presets button in the title bar, and then when opening to browse the assets, it also displays some info to distinguish the difference, such as Select Material, not object, or maybe it simply adds it to your scene's asset library, which would be non-destructive, but also less obvious what was going on (and require that the scene be saved).

**Comment by vilemduha** [comment]
Just to notify, we're actually working on this feature now. It should be wider, not only GN or shading nodes, but general extension of the asset types we support, there are many untackled areas. The big question is for us not what to add, but how to organize things so they are readable also for beginners. Since we serve all levels of Blender users, and don't want to overwhelm some of them.
